"""Add flexible group size to Quote

Revision ID: 403ce28f0801
Revises: a6c751055c4e
Create Date: 2025-05-15 18:35:12.510006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403ce28f0801'
down_revision = 'a6c751055c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quoted_passenger_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quoted_passenger_max', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('booking_type', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_column('booking_type')
        batch_op.drop_column('quoted_passenger_max')
        batch_op.drop_column('quoted_passenger_min')

    # ### end Alembic commands ###
